"""
Build-time helper: read the raw Anthropic API key from .build_key.txt
(gitignored, owner-only) and write key_store.py (gitignored) with an
XOR + base64 obfuscated copy. PyInstaller then bundles key_store.py
into the .exe so employees never see the plaintext.

Usage:
    python make_key_store.py
    python make_key_store.py --key sk-ant-...    # override file lookup
"""

import argparse
import base64
import sys
from pathlib import Path

PASSPHRASE = "shein-extract-2026"
HERE = Path(__file__).resolve().parent
RAW_KEY_FILE = HERE / ".build_key.txt"
OUTPUT_FILE = HERE / "key_store.py"


def encode(raw_key: str) -> str:
    if not raw_key:
        return ""
    out = bytearray()
    for i, ch in enumerate(raw_key.encode("utf-8")):
        out.append(ch ^ ord(PASSPHRASE[i % len(PASSPHRASE)]))
    return base64.b64encode(bytes(out)).decode("ascii")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", help="Raw API key. If omitted, reads .build_key.txt")
    args = ap.parse_args()

    key = (args.key or "").strip()
    if not key:
        if not RAW_KEY_FILE.exists():
            print(f"[error] {RAW_KEY_FILE.name} not found.", file=sys.stderr)
            print("Create that file with the raw Anthropic API key on one line, "
                  "or pass --key sk-ant-...", file=sys.stderr)
            sys.exit(1)
        key = RAW_KEY_FILE.read_text(encoding="utf-8").strip()

    if not key.startswith("sk-ant-"):
        print(f"[error] Key doesn't look like an Anthropic key (must start "
              f"with 'sk-ant-'). Got: {key[:10]}...", file=sys.stderr)
        sys.exit(1)

    encoded = encode(key)

    OUTPUT_FILE.write_text(
        '"""Auto-generated by make_key_store.py — DO NOT EDIT, DO NOT COMMIT."""\n'
        f'ENCODED_KEY = "{encoded}"\n'
        f'PASSPHRASE = "{PASSPHRASE}"\n'
        '\n'
        'def get_obfuscated_key() -> str:\n'
        '    if not ENCODED_KEY:\n'
        '        return ""\n'
        '    import base64\n'
        '    try:\n'
        '        raw = base64.b64decode(ENCODED_KEY)\n'
        '        out = bytearray()\n'
        '        for i, b in enumerate(raw):\n'
        '            out.append(b ^ ord(PASSPHRASE[i % len(PASSPHRASE)]))\n'
        '        return out.decode("utf-8")\n'
        '    except Exception:\n'
        '        return ""\n',
        encoding="utf-8",
    )
    print(f"  wrote {OUTPUT_FILE.name} ({len(encoded)} encoded chars)")


if __name__ == "__main__":
    main()
