"""
AU setup wizard (Tkinter, 5 steps).

Writes %APPDATA%\\shein-extract-au\\config.env with the user's choices.
Steps:
  1. Welcome
  2. System check (Chrome)
  3. Path config (3 fields)
  4. Anthropic API key
  5. Done (write config.env)
"""
import os
import re
import sys
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

from chrome_finder import find_chrome as _shared_find_chrome

USER_DATA_DIR = Path(os.environ.get("APPDATA", str(Path.home()))) / "shein-extract-au"
CONFIG_FILE = USER_DATA_DIR / "config.env"

# Default starting point for SUBMITTED_DIR — same default config.py uses
DEFAULT_SUBMITTED_DIR = r"D:\共享云端硬盘\02 希音\澳洲站"

# ── Pure helpers ─────────────────────────────────────────────────────────────


def write_config_env(values: dict, path: Path | None = None) -> Path:
    """Write KEY=VALUE lines (UTF-8). Creates parent dirs."""
    p = path or CONFIG_FILE
    p.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by SheinExtractAU setup wizard. Edit by re-running the wizard",
        "# or by deleting this file before launching the app.",
        "",
    ]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    lines.append("")
    p.write_text("\n".join(lines), encoding="utf-8")
    return p


def load_existing_config(path: Path | None = None) -> dict:
    """Parse a KEY=VALUE config.env file back to a dict. Missing file → {}."""
    p = path or CONFIG_FILE
    if not p.exists():
        return {}
    out = {}
    try:
        text = p.read_text(encoding="utf-8")
    except OSError:
        return {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def is_first_run_complete(path: Path | None = None) -> bool:
    p = path or CONFIG_FILE
    if not p.exists():
        return False
    try:
        text = p.read_text(encoding="utf-8")
    except OSError:
        return False
    return bool(re.search(r"^\s*SHEIN_SUBMITTED_DIR\s*=\s*\S", text, re.M))


def mask_api_key(key: str) -> str:
    """sk-ant-api03-xxxxxxxx → sk-ant-a...xxxx style. Short/empty unchanged."""
    if not key or len(key) < 16:
        return key
    return f"{key[:8]}...{key[-4:]}"


def find_chrome() -> str | None:
    """Delegate to chrome_finder — kept here so tests can monkeypatch this name."""
    return _shared_find_chrome()


# ── Wizard (Tkinter) ─────────────────────────────────────────────────────────


class Wizard:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("SHEIN 上架工具 AU — 配置")
        self.root.geometry("680x500")
        self.root.resizable(False, False)
        try:
            self.root.attributes("-topmost", True)
            self.root.after(500, lambda: self.root.attributes("-topmost", False))
        except Exception:
            pass

        self.completed = False
        self.cancelled = False

        self.values = {
            "submitted_dir": DEFAULT_SUBMITTED_DIR,
            "output_dir": "",
            "input_filename": "希音链接 - LU.xlsx",
            "output_filename": "",
            "api_key": "",
        }
        self._load_existing()

        self.frame = ttk.Frame(self.root, padding=20)
        self.frame.pack(fill="both", expand=True)

        self.steps = [
            self._step_welcome,
            self._step_check,
            self._step_paths,
            self._step_api,
            self._step_done,
        ]
        self.step_idx = 0
        self._render()

    def _load_existing(self) -> None:
        cfg = load_existing_config()
        mapping = {
            "SHEIN_SUBMITTED_DIR": "submitted_dir",
            "SHEIN_OUTPUT_DIR": "output_dir",
            "SHEIN_INPUT_FILENAME": "input_filename",
            "SHEIN_OUTPUT_FILENAME": "output_filename",
            "ANTHROPIC_API_KEY": "api_key",
        }
        for env_k, state_k in mapping.items():
            if env_k in cfg:
                self.values[state_k] = cfg[env_k]

    def _clear(self):
        for w in self.frame.winfo_children():
            w.destroy()

    def _render(self):
        self._clear()
        self.steps[self.step_idx]()

    def _next(self):
        if self.step_idx < len(self.steps) - 1:
            self.step_idx += 1
            self._render()

    def _back(self):
        if self.step_idx > 0:
            self.step_idx -= 1
            self._render()

    def _heading(self, text):
        ttk.Label(self.frame, text=text,
                  font=("Microsoft YaHei", 16, "bold")).pack(anchor="w", pady=(0, 6))
        ttk.Separator(self.frame, orient="horizontal").pack(fill="x", pady=(0, 12))

    def _para(self, text):
        ttk.Label(self.frame, text=text, wraplength=620, justify="left",
                  font=("Microsoft YaHei", 10)).pack(anchor="w", pady=(0, 8))

    def _nav(self, on_next=None, next_text="下一步", show_back=True):
        bar = ttk.Frame(self.frame)
        bar.pack(side="bottom", fill="x", pady=(20, 0))
        ttk.Button(bar, text="取消", command=self._cancel).pack(side="left")
        if show_back and self.step_idx > 0:
            ttk.Button(bar, text="上一步", command=self._back).pack(side="right", padx=4)
        if on_next:
            ttk.Button(bar, text=next_text, command=on_next).pack(side="right", padx=4)

    def _cancel(self):
        if messagebox.askyesno("确认", "现在退出向导？未保存的修改会丢失。"):
            self.cancelled = True
            self.root.destroy()

    # Steps ───────────────────────────────────────────────────────────────────
    def _step_welcome(self):
        self._heading("SHEIN 上架工具 AU — 配置")
        self._para(
            "这个向导帮你配置输入/输出目录和 API key（约 1-2 分钟）。\n\n"
            "你已经配置过的值会预填进来。点【开始】继续。"
        )
        self._nav(on_next=self._next, next_text="开始", show_back=False)

    def _step_check(self):
        self._heading("系统检查")
        chrome = find_chrome()
        if chrome:
            ttk.Label(self.frame, text=f"✓ 找到 Chrome：{chrome}",
                      foreground="green", font=("Microsoft YaHei", 10),
                      wraplength=620, justify="left").pack(anchor="w", pady=4)
            self._nav(on_next=self._next)
        else:
            ttk.Label(self.frame,
                      text=(
                          "✗ 未找到 Chrome。\n"
                          "  · 常规做法：装 https://www.google.com/chrome/ 后重开向导。\n"
                          "  · 如果 Chrome 已装在非标准路径（便携版、D 盘等），\n"
                          "    设环境变量 SHEIN_CHROME_PATH 指向 chrome.exe 后重开向导。"
                      ),
                      foreground="red", font=("Microsoft YaHei", 10),
                      wraplength=620, justify="left").pack(anchor="w", pady=4)
            self._nav(on_next=None)

    def _step_paths(self):
        self._heading("路径设置")
        self._para("确认或修改以下 4 项。")

        rows = [
            ("输入表所在目录", "submitted_dir", True),
            ("输出根目录（留空 = 与输入目录相同；店铺名自动作为子文件夹）", "output_dir", True),
            ("主表(输入)文件名（必填，例: 澳洲希音链接 (输入) - ZR.xlsx）", "input_filename", False),
            ("富表(输出)文件名（必填，例: 澳洲希音链接 (输出) - ZR.xlsx）", "output_filename", False),
        ]
        self._entries = {}
        for label, key, browseable in rows:
            row = ttk.Frame(self.frame)
            row.pack(fill="x", pady=4)
            ttk.Label(row, text=label, width=30, anchor="w",
                      font=("Microsoft YaHei", 10)).pack(side="left")
            var = tk.StringVar(value=self.values.get(key, ""))
            ttk.Entry(row, textvariable=var, font=("Consolas", 9)).pack(
                side="left", fill="x", expand=True, padx=4)
            self._entries[key] = var
            if browseable:
                ttk.Button(row, text="浏览...",
                           command=lambda v=var: self._browse(v)).pack(side="left")

        def on_next():
            for k, var in self._entries.items():
                self.values[k] = var.get().strip()
            sd = Path(self.values["submitted_dir"])
            if not sd.is_dir():
                messagebox.showerror("路径错误", f"输入目录不存在:\n{sd}")
                return
            if not self.values["input_filename"]:
                messagebox.showerror("配置缺失", "请填写'主表(输入)文件名'。")
                return
            if not self.values["output_filename"]:
                messagebox.showerror("配置缺失", "请填写'富表(输出)文件名'。")
                return
            if not self.values["output_dir"]:
                # 默认：输出根 = 输入目录。跑起来后会在这下面自动建 <店铺名>/
                # 每个 xlsx 的每个 sheet 会成为一层子文件夹。
                self.values["output_dir"] = str(sd)
            od = Path(self.values["output_dir"])
            try:
                od.mkdir(parents=True, exist_ok=True)
            except OSError as e:
                messagebox.showerror("无法创建输出目录", str(e))
                return
            self._next()

        self._nav(on_next=on_next)

    def _browse(self, var: tk.StringVar):
        cur = var.get() or os.path.expanduser("~")
        d = filedialog.askdirectory(initialdir=cur, title="选择文件夹")
        if d:
            var.set(d)

    def _step_api(self):
        self._heading("Anthropic API Key")
        self._para(
            "用于 Claude Haiku 生成 eBay 标题。可以留空（不启用 AI 标题）。"
        )
        existing = self.values.get("api_key", "")
        if existing:
            self._para(f"现有 key：{mask_api_key(existing)}\n"
                       f"输入 “keep” 或留空 = 保留现值。")
        var = tk.StringVar(value="")
        ttk.Entry(self.frame, textvariable=var, font=("Consolas", 9),
                  width=70).pack(anchor="w", pady=4)

        def on_next():
            v = var.get().strip()
            if v and v.lower() != "keep":
                self.values["api_key"] = v
            # else keep existing
            self._next()

        self._nav(on_next=on_next)

    def _step_done(self):
        self._heading("完成")
        env_values = {
            "SHEIN_SUBMITTED_DIR": self.values["submitted_dir"],
            "SHEIN_OUTPUT_DIR": self.values["output_dir"],
            "SHEIN_INPUT_FILENAME": self.values["input_filename"],
            "SHEIN_OUTPUT_FILENAME": self.values["output_filename"],
        }
        if self.values["api_key"]:
            env_values["ANTHROPIC_API_KEY"] = self.values["api_key"]
        try:
            written = write_config_env(env_values)
            self._para(f"配置已保存到：\n  {written}")
        except OSError as e:
            messagebox.showerror("保存失败", str(e))
            return

        bar = ttk.Frame(self.frame)
        bar.pack(side="bottom", fill="x", pady=(20, 0))
        ttk.Button(bar, text="关闭", command=self._finish).pack(side="right", padx=4)

    def _finish(self):
        self.completed = True
        self.root.destroy()

    def run(self) -> bool:
        self.root.mainloop()
        return self.completed and not self.cancelled


def run_wizard() -> bool:
    return Wizard().run()


if __name__ == "__main__":
    sys.exit(0 if run_wizard() else 1)
